### ISSUE TITLE
error loading plugin with version 3

### ISSUE THREAD

**Issue by jmissig** [smockle/homebridge-lutron-caseta#43]
**Node.js version:**
v12.16.3

**Plugin version:**
homebridge-lutron-caseta-smockle@3.0.1

Updated to the new 3.x version, now I’m getting:

```
Apr 29 18:19:39 saga homebridge[5678]: [4/29/2020, 6:19:39 PM] ERROR LOADING PLUGIN homebridge-lutron-caseta-smockle:
Apr 29 18:19:39 saga homebridge[5678]: [4/29/2020, 6:19:39 PM] Error: Cannot find module '/home/nodejs/node_modules/lib/node_modules/homebridge-lutron-caseta-smockle/dist/src/index.js'
Apr 29 18:19:39 saga homebridge[5678]: Require stack:
Apr 29 18:19:39 saga homebridge[5678]: - /home/nodejs/node_modules/lib/node_modules/homebridge/lib/plugin.js
Apr 29 18:19:39 saga homebridge[5678]: - /home/nodejs/node_modules/lib/node_modules/homebridge/lib/pluginManager.js
Apr 29 18:19:39 saga homebridge[5678]: - /home/nodejs/node_modules/lib/node_modules/homebridge/lib/api.js
Apr 29 18:19:39 saga homebridge[5678]: - /home/nodejs/node_modules/lib/node_modules/homebridge/lib/index.js
Apr 29 18:19:39 saga homebridge[5678]: - /home/nodejs/node_modules/lib/node_modules/homebridge/lib/cli.js
Apr 29 18:19:39 saga homebridge[5678]: - /home/nodejs/node_modules/lib/node_modules/homebridge/bin/homebridge
Apr 29 18:19:39 saga homebridge[5678]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
Apr 29 18:19:39 saga homebridge[5678]:     at Function.Module._load (internal/modules/cjs/loader.js:840:27)
Apr 29 18:19:39 saga homebridge[5678]:     at Module.require (internal/modules/cjs/loader.js:1019:19)
Apr 29 18:19:39 saga homebridge[5678]:     at require (internal/modules/cjs/helpers.js:77:18)
Apr 29 18:19:39 saga homebridge[5678]:     at Plugin.load (/home/nodejs/node_modules/lib/node_modules/homebridge/src/plugin.ts:162:27)
Apr 29 18:19:39 saga homebridge[5678]:     at /home/nodejs/node_modules/lib/node_modules/homebridge/src/pluginManager.ts:119:16
Apr 29 18:19:39 saga homebridge[5678]:     at Map.forEach (<anonymous>)
Apr 29 18:19:39 saga homebridge[5678]:     at PluginManager.initializeInstalledPlugins (/home/nodejs/node_modules/lib/node_modules/homebridge/src/pluginManager.ts:117:18)
Apr 29 18:19:39 saga homebridge[5678]:     at Server.start (/home/nodejs/node_modules/lib/node_modules/homebridge/src/server.ts:148:24)
Apr 29 18:19:39 saga homebridge[5678]:     at cli (/home/nodejs/node_modules/lib/node_modules/homebridge/src/cli.ts:78:10)
```

**Comment by smockle** [comment]
Thanks for reporting this @jmissig! I’d gotten some paths mixed up. 😬 I just merged #44 to fix the issue and published version `3.0.2` with the fix.

**Comment by jmissig** [comment]
Hrm, still no go for me:
```
Apr 29 19:23:35 saga homebridge[7204]: [4/29/2020, 7:23:35 PM] Error loading platform requested in your config.json at position 6
Apr 29 19:23:35 saga homebridge[7204]: [4/29/2020, 7:23:35 PM] Error: The requested platform 'LutronCasetaPlatform' was not registered by any plugin.
Apr 29 19:23:35 saga homebridge[7204]:     at PluginManager.getPluginForPlatform (/home/nodejs/node_modules/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
Apr 29 19:23:35 saga homebridge[7204]:     at /home/nodejs/node_modules/lib/node_modules/homebridge/src/server.ts:385:37
Apr 29 19:23:35 saga homebridge[7204]:     at Array.forEach (<anonymous>)
Apr 29 19:23:35 saga homebridge[7204]:     at Server.loadPlatforms (/home/nodejs/node_modules/lib/node_modules/homebridge/src/server.ts:372:27)
Apr 29 19:23:35 saga homebridge[7204]:     at Server.start (/home/nodejs/node_modules/lib/node_modules/homebridge/src/server.ts:151:29)
Apr 29 19:23:35 saga homebridge[7204]:     at cli (/home/nodejs/node_modules/lib/node_modules/homebridge/src/cli.ts:78:10)
Apr 29 19:23:35 saga homebridge[7204]:     at Object.<anonymous> (/home/nodejs/node_modules/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 29 19:23:35 saga homebridge[7204]:     at Module._compile (internal/modules/cjs/loader.js:1133:30)
Apr 29 19:23:35 saga homebridge[7204]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
Apr 29 19:23:35 saga homebridge[7204]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Apr 29 19:23:35 saga homebridge[7204]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Apr 29 19:23:35 saga homebridge[7204]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Apr 29 19:23:35 saga homebridge[7204]:     at internal/main/run_main_module.js:18:47
```

**Comment by jmissig** [comment]
Oh this is more likely the actual error that would help:
```
Apr 29 19:25:07 saga homebridge[7347]: [4/29/2020, 7:25:07 PM] ERROR LOADING PLUGIN homebridge-lutron-caseta-smockle:
Apr 29 19:25:07 saga homebridge[7347]: [4/29/2020, 7:25:07 PM] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/nodejs/node_modules/lib/node_modules/homebridge-lutron-caseta-smockle/dist/index.js
Apr 29 19:25:07 saga homebridge[7347]: require() of ES modules is not supported.
Apr 29 19:25:07 saga homebridge[7347]: require() of /home/nodejs/node_modules/lib/node_modules/homebridge-lutron-caseta-smockle/dist/index.js from /home/nodejs/node_modules/lib/node_modules/homebridge/lib/plugin.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Apr 29 19:25:07 saga homebridge[7347]: Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/nodejs/node_modules/lib/node_modules/homebridge-lutron-caseta-smockle/package.json.
Apr 29 19:25:07 saga homebridge[7347]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1149:13)
Apr 29 19:25:07 saga homebridge[7347]:     at Module.load (internal/modules/cjs/loader.js:977:32)
Apr 29 19:25:07 saga homebridge[7347]:     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
Apr 29 19:25:07 saga homebridge[7347]:     at Module.require (internal/modules/cjs/loader.js:1019:19)
Apr 29 19:25:07 saga homebridge[7347]:     at require (internal/modules/cjs/helpers.js:77:18)
Apr 29 19:25:07 saga homebridge[7347]:     at Plugin.load (/home/nodejs/node_modules/lib/node_modules/homebridge/src/plugin.ts:162:27)
Apr 29 19:25:07 saga homebridge[7347]:     at /home/nodejs/node_modules/lib/node_modules/homebridge/src/pluginManager.ts:119:16
Apr 29 19:25:07 saga homebridge[7347]:     at Map.forEach (<anonymous>)
Apr 29 19:25:07 saga homebridge[7347]:     at PluginManager.initializeInstalledPlugins (/home/nodejs/node_modules/lib/node_modules/homebridge/src/pluginManager.ts:117:18)
Apr 29 19:25:07 saga homebridge[7347]:     at Server.start (/home/nodejs/node_modules/lib/node_modules/homebridge/src/server.ts:148:24)
```

**Comment by smockle** [comment]
Thanks again @jmissig! I fixed that issue in https://github.com/smockle/homebridge-lutron-caseta/pull/45, which was published as version `3.0.3`.

**Comment by jmissig** [comment]
thank you!

**Comment by jmissig** [comment]
Ok! Up and running with 3.0.3. And the Pico Remotes work. Whew!

**Comment by smockle** [comment]
Awesome, thanks for the update! I apologize for the rocky transition, and I appreciate your patience and assistance tracking down these bugs. 🙌
